POST http://localhost:5193/JobsSearch/Search
Content-Type: application/json
{
  "KeyWords": ["javascript"],
  "Companies": ["https://www.jobsearch.az/vacancies"],
  "SearchNow": true,
  "ScheduleTime": null
}